### ISSUE TITLE
Feature : Use vector image or input and output

### ISSUE THREAD

**Issue by grogcw** [nuno-faria/tiler#25]
Hi !
I find this project very attractive artisticly-wise, and I was wondering how big of a deal it would be to use SVGs images as an input in order to have scalable vector graphics at the output.

I know it might sound far-fetched, but are you (or can you) consider it ?

Thanks for your great work,

Cheers !

**Comment by nuno-faria** [comment]
Thanks for the feedback.

That would be a pretty cool idea. Unfortunately, manipulating SVG would be totally different from other formats like PNG or JPG (vectors vs pixels). Also, my quick search shows that opencv2 doesn't support SVG, and there doesn't seem to be another library that could be used as replacement.

With that being said, since the images generated are usually simple (circles, paper clips, letters, ...), one could use programs like Inkscape or websites like [VectorMagic](https://vectormagic.com/) to convert a PNG to SVG (with pretty good results). For more info on this check this [SO question](https://stackoverflow.com/questions/1861382/how-to-convert-a-png-image-to-a-svg).
