### ISSUE TITLE
It takes a long time

### ISSUE THREAD

**Issue by Dabao55** [nuno-faria/tiler#44]
I'm working with a 960 * 960 pixel image with circle_100 tile,  it takes me about 20 mins. Is it because of the poor performance of my computer? Can I accelerate it with GPU? Looking forward your reply.

**Comment by nuno-faria** [comment]
Unfortunately, this is a CPU only implementation, which means it cannot be GPU accelerated. To improve performance, you can try three things:
- Increase the `PIXEL_SHIFT` config, since a smaller `PIXEL_SHIFT` will require more computations (or maybe even set it to `None` to be the same size as the tile);
- Reduce the number of `RESIZING_SCALES`;
- Increase the `POOL_SIZE` to match the number of CPU cores.

Hope this helps.
